api:
  award-notification:
    queue-name: AWARDS

server:
  port: 3000
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password